[versions]
agp = "8.4.1"
kotlin = "2.0.21"
compose-multiplatform = "1.7.0"
android-minSdk = "24"
android-targetSdk = "35"
android-compileSdk = "35"
androidx-activityCompose = "1.9.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
