[versions]
agp = "8.4.1"
kotlin = "2.0.21"
compose-multiplatform = "1.7.0"
android-minSdk = "24"
android-targetSdk = "35"
android-compileSdk = "35"
androidx-activityCompose = "1.9.2"
play-services-location = "21.3.0"
kotlinx-datetime = "0.6.1"
sqldelight = "2.0.2"
ktor = "3.0.3"
kotlinx-serialization = "1.7.3"
astronomy = "v2.1.19"
camera = "1.4.1"
coil = "3.0.4"
markdownRenderer = "0.27.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
astronomy = { module = "com.github.cosinekitty:astronomy", version.ref = "astronomy" }
camera-core     = { module = "androidx.camera:camera-core",      version.ref = "camera" }
camera-camera2  = { module = "androidx.camera:camera-camera2",   version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view     = { module = "androidx.camera:camera-view",      version.ref = "camera" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
markdown-renderer = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdownRenderer" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
