package com.islandskiesastro.astroplanner

import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Verifies getPlanetRaDecForD against reference values generated by the
 * cosinekitty/astronomy library (see PlanetRaDecReferenceGenerator in androidUnitTest).
 *
 * Epoch 1: 2026-03-14 00:00:00 UTC  (ms=1741910400000, d=9203.5)
 * Epoch 2: 2025-07-04 12:00:00 UTC  (ms=1751630400000, d=9316.0)
 *
 * Tolerances: inner planets (Mercury, Venus, Mars) ±2°, outer planets ±1°.
 * Schlyter algorithm nominal accuracy is ~1° inner, ~0.5° outer.
 */
class AstronomyServiceTest {

    private val epoch1D = 9203.5
    private val epoch2D = 9316.0

    // ── Reference values from cosinekitty astronomy library ───────────────────

    private val refEpoch1 = mapOf(
        "mercury" to Pair(  7.504,   6.531),
        "venus"   to Pair(  3.876,  10.837),
        "mars"    to Pair(110.885,  25.239),
        "jupiter" to Pair( 72.195,  22.070),
        "saturn"  to Pair(353.676,  -4.821),
        "uranus"  to Pair( 51.711,  18.559),
        "neptune" to Pair(359.931,  -1.402),
    )

    private val refEpoch2 = mapOf(
        "mercury" to Pair(131.113,  18.019),
        "venus"   to Pair( 58.222,  17.612),
        "mars"    to Pair(161.720,   8.789),
        "jupiter" to Pair( 96.107,  23.195),
        "saturn"  to Pair(  2.610,  -1.324),
        "uranus"  to Pair( 57.732,  19.919),
        "neptune" to Pair(  2.525,  -0.348),
    )

    // ── Helpers ───────────────────────────────────────────────────────────────

    private fun raDiff(a: Double, b: Double): Double {
        var d = (a - b + 360.0) % 360.0
        if (d > 180.0) d -= 360.0
        return abs(d)
    }

    private fun assertPlanet(
        planetId: String,
        d: Double,
        expectedRa: Double,
        expectedDec: Double,
        toleranceDeg: Double
    ) {
        val (ra, dec) = AstronomyService.getPlanetRaDecForD(planetId, d)
        val dRa  = raDiff(ra, expectedRa)
        val dDec = abs(dec - expectedDec)
        assertTrue(
            dRa  <= toleranceDeg,
            "$planetId d=$d: RA $ra° expected $expectedRa° (Δ=${"%.3f".format(dRa)}° > tolerance $toleranceDeg°)"
        )
        assertTrue(
            dDec <= toleranceDeg,
            "$planetId d=$d: Dec $dec° expected $expectedDec° (Δ=${"%.3f".format(dDec)}° > tolerance $toleranceDeg°)"
        )
    }

    // ── Epoch 1: 2026-03-14 00:00 UTC ─────────────────────────────────────────

    @Test fun mercury_epoch1() = assertPlanet("mercury",  epoch1D, refEpoch1["mercury"]!!.first, refEpoch1["mercury"]!!.second, 2.0)
    @Test fun venus_epoch1()   = assertPlanet("venus",    epoch1D, refEpoch1["venus"]!!.first,   refEpoch1["venus"]!!.second,   2.0)
    @Test fun mars_epoch1()    = assertPlanet("mars",     epoch1D, refEpoch1["mars"]!!.first,    refEpoch1["mars"]!!.second,    2.0)
    @Test fun jupiter_epoch1() = assertPlanet("jupiter",  epoch1D, refEpoch1["jupiter"]!!.first, refEpoch1["jupiter"]!!.second, 1.0)
    @Test fun saturn_epoch1()  = assertPlanet("saturn",   epoch1D, refEpoch1["saturn"]!!.first,  refEpoch1["saturn"]!!.second,  1.0)
    @Test fun uranus_epoch1()  = assertPlanet("uranus",   epoch1D, refEpoch1["uranus"]!!.first,  refEpoch1["uranus"]!!.second,  1.0)
    @Test fun neptune_epoch1() = assertPlanet("neptune",  epoch1D, refEpoch1["neptune"]!!.first, refEpoch1["neptune"]!!.second, 1.0)

    // ── Epoch 2: 2025-07-04 12:00 UTC ─────────────────────────────────────────

    @Test fun mercury_epoch2() = assertPlanet("mercury",  epoch2D, refEpoch2["mercury"]!!.first, refEpoch2["mercury"]!!.second, 2.0)
    @Test fun venus_epoch2()   = assertPlanet("venus",    epoch2D, refEpoch2["venus"]!!.first,   refEpoch2["venus"]!!.second,   2.0)
    @Test fun mars_epoch2()    = assertPlanet("mars",     epoch2D, refEpoch2["mars"]!!.first,    refEpoch2["mars"]!!.second,    2.0)
    @Test fun jupiter_epoch2() = assertPlanet("jupiter",  epoch2D, refEpoch2["jupiter"]!!.first, refEpoch2["jupiter"]!!.second, 1.0)
    @Test fun saturn_epoch2()  = assertPlanet("saturn",   epoch2D, refEpoch2["saturn"]!!.first,  refEpoch2["saturn"]!!.second,  1.0)
    @Test fun uranus_epoch2()  = assertPlanet("uranus",   epoch2D, refEpoch2["uranus"]!!.first,  refEpoch2["uranus"]!!.second,  1.0)
    @Test fun neptune_epoch2() = assertPlanet("neptune",  epoch2D, refEpoch2["neptune"]!!.first, refEpoch2["neptune"]!!.second, 1.0)

    // ── Unknown planet returns (0, 0) ─────────────────────────────────────────

    @Test fun unknown_planet_returns_zero() {
        val (ra, dec) = AstronomyService.getPlanetRaDecForD("pluto", epoch1D)
        assertTrue(ra == 0.0 && dec == 0.0, "Unknown planet should return (0.0, 0.0)")
    }
}
